### ISSUE TITLE
Safari 11 support

### ISSUE THREAD

**Issue by dracos** [mfranzke/loading-attribute-polyfill#6] opened 2019-08-15 15:50 UTC
Had a bug report of a JS error in Safari 11: https://twitter.com/librarythingtim/status/1162019922089828355 - to me it looks like `IntersectionObserver in window` returns false in Safari 11, so I'm not sure how this code got reached.

**Comment by mfranzke** [comment] 2019-08-15 16:11
I‘ll look into it and come back with a feedback asap.

**Comment by mfranzke** [comment] 2019-08-15 17:53
The fastest solution is to include an IntersectionObserver polyfill - but as written before, the problem is even also already fixed by commit 711efec410a20d6677e44dbdf2ba2cc93c7015d9, and will get released asap with a new version.

**Comment by mfranzke** [comment] 2019-08-15 18:22
... and the flexibility not to include that IntersectionObserver polyfill is now included within the new version 1.1.0

**Closed by mfranzke** 2019-08-15 18:22 UTC
Labels: bug
